// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFvCa9Y8EsDqaiAafQBDs3VldoX2n97ew',
    appId: '1:111034042086:web:13eff8806a66d25db31d27',
    messagingSenderId: '111034042086',
    projectId: 'fyp-db-35afc',
    authDomain: 'fyp-db-35afc.firebaseapp.com',
    storageBucket: 'fyp-db-35afc.appspot.com',
    measurementId: 'G-31D5MLGTRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7bpsmeCafiHSCq3Qk94uxf9luwao4gi8',
    appId: '1:111034042086:android:6bbdb1f27dc8129eb31d27',
    messagingSenderId: '111034042086',
    projectId: 'fyp-db-35afc',
    storageBucket: 'fyp-db-35afc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASDAbUh7aDusaL-cXzDmod0uVb2Qw0jj0',
    appId: '1:111034042086:ios:2fe1da8817a8c568b31d27',
    messagingSenderId: '111034042086',
    projectId: 'fyp-db-35afc',
    storageBucket: 'fyp-db-35afc.appspot.com',
    iosClientId: '111034042086-hb1ed33pl5v7jia6og8rt9547i7ranbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASDAbUh7aDusaL-cXzDmod0uVb2Qw0jj0',
    appId: '1:111034042086:ios:2fe1da8817a8c568b31d27',
    messagingSenderId: '111034042086',
    projectId: 'fyp-db-35afc',
    storageBucket: 'fyp-db-35afc.appspot.com',
    iosClientId: '111034042086-hb1ed33pl5v7jia6og8rt9547i7ranbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatapp',
  );
}
